FROM openjdk:windowsservercore
EXPOSE 8080
ADD /target/employeespringservice-0.0.1-SNAPSHOT.jar employeespringservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","employeespringservice-0.0.1-SNAPSHOT.jar"]